FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the source code
COPY . .

# Expose the development server port
EXPOSE 4200

# Start Angular in development mode (live reload)
CMD ["npm", "run", "start"]
